### ISSUE TITLE
A lot of the links refer to index.html

### ISSUE THREAD

**Issue by Klap-in** [dokuwiki/dokuwiki-plugin-xref#3]
The referring is not that useful at the moment, because it points often to index.html

The patch might be broken again?

Seems it is working sometimes. Not clear when/when not.
Maybe related to old and newer version of the code?

**Comment by splitbrain** [comment]
I think phpxref simply doesn't work very well with modern PHP. Maybe it's time to retire it in favor of https://codesearch.dokuwiki.org/xref/dokuwiki/
